#!/bin/sh

# svn-ignore

# usage:
#   svn-ignore [file or dir]

for f; do
    d=`dirname "$f"`
    b=`basename "$f"`
    ignore=`svn pg svn:ignore "$d"`
    if [ -n "$ignore" ]; then
        ignore="$ignore
"
    fi
    ignore="$ignore$b"
    svn ps svn:ignore "$ignore" "$d"
done
